### ISSUE TITLE
Let's get started

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/cdav-library#1]
Replacement for https://github.com/georgehrke/js-caldav-lib/issues/1

**Comment by tcitworld** [comment]
Correct me if I'm wrong, but 

> I wouldn't even provide the flat models, but just the models that represent the CalDAV / CardDAV models.

would actually be something like https://github.com/nextcloud/contacts/blob/master/js/dav/lib/model.js ? 

What should be here is basically : 
1. Those models
2. The services to use those models
3. The xml templates

And nothing else.

**Comment by georgehrke** [comment]
> would actually be something like https://github.com/nextcloud/contacts/blob/master/js/dav/lib/model.js ?

Maybe not that slim.
These models should have `update()`, `delete()`, `share()`, `unshare()`, `publish()` and `unpublish()` methods and also the `updateNotifier` I talked about in georgehrke/js-caldav-lib#1

We would also need custom setters if we want to keep track of what was changed. (so we only send changed properties in a `PROPPATCH` request)

**Comment by skjnldsv** [comment]
Okay, after a lot of digging, I disagree with what we were going for.
We should keep things separate
![untitled diagram](https://user-images.githubusercontent.com/14975046/42313028-06fb3698-8042-11e8-8981-b8bdfe6318b3.png)


We shouldn't mix the vcard/ical parser with some functions to manage the webdav backend. This is confusing and harder to maintain.

Since we're actually going for this pretty soon (next week), I'm gonna start working on the vcard parser-formater and we'll integrate the iCal to the same lib later (don't have the time nor the knowledge of the iCal format to properly implement both at the same time :) )
