### ISSUE TITLE
Make a proper module of it?

### ISSUE THREAD

**Issue by hoonto** [nextcloud/cdav-library#325]
Just writing a quick note to ask if there's some kind of reason this has not been published to npm registry (or maybe it is published but I have missed it)? Would be good to rely on semver and install easily into projects.

**Comment by georgehrke** [comment]
It has not been published, because it's been developed solely for the purpose of using it in the Calendar / Contacts / Tasks app. I have no intention of supporting it for any other use-case.

If we put it on npm, people will just see CalDAV/CardDAV, install it and we will receive issues for things this library was never build for.

**Comment by hoonto** [comment]
That makes sense, thanks for the explanation!
