### ISSUE TITLE
Wrong Content-Type request header in PUT requests

### ISSUE THREAD

**Issue by sreith1** [nextcloud/cdav-library#539]
#### Case 1
1. Open Tasks list in browser
2. Check existing task

#### Case 2
1. Open Tasks list in browser
2. Open details of existing task
3. Rename task
4. Apply

### Expected behaviour
Created PUT request header should have `Content-Type` `text/calendar; charset=utf-8`.

### Actual behaviour
Created PUT request header has `Content-Type` `application/xml; charset=utf-8`. The request data is an iCalendar string, which is not XML.

### Why is that a problem?
ModSecurity Web Application Firewall (as used in NextCloudPi) fails trying to parse incoming XML data.

### Client configuration
**Browser:** Firefox 91.0
**Operating system:** Linux Mint 20

**Comment by tcitworld** [comment]
WebDAV states [which states](https://datatracker.ietf.org/doc/html/rfc4918#section-8.2)
>When XML is used for a *request or response body*, the Content-Type type SHOULD be application/xml.

An example in the CalDAV RFC shows the content-type for a `PUT` request as `text/calendar`: https://datatracker.ietf.org/doc/html/rfc4791#section-5.3.2. Sabre has something similar: https://sabre.io/dav/building-a-caldav-client/#creating-a-calendar-object

So I'd say the issue is valid. :+1:

**Comment by sreith1** [comment]
Thanks for your work! Tasks works fine now (and ModSecurity also accepts the requests).

Nevertheless, the same problem occurs in Calendar app 2.3.3. While the correct `Content-Type` is send while creating a new event, after changing the name of an event the PUT request sends an `application/xml;`. I guess the Calendar app uses this same library?

**Comment by raimund-schluessler** [comment]
The Calendar app uses the same library, but the fix is not in 2.3.3 yet. This should work with one of the next releases.
